version: '3.9'

networks:
  e-commerce:

services:

  banco-postgres:
    image: postgres:14-alpine
    container_name: "banco-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=e_commerce
    ports:
      - "5432:5432"
    networks:
      - e-commerce

  banco-mongo:
    image: mongo
    container_name: "banco-mongo"
    ports:
      - "27017:27017"
    networks:
      - e-commerce

  gateway:
    container_name: "gateway"
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      MS_USER_URI: ms-user
      MS_GESTAO_ITENS_URI: gestao-itens
      MS_CARRINHO_COMPRAS_URI: carrinho-compras
      MS_PAGAMENTO_URI: ms-pagamento
    networks:
      - e-commerce

  ms-user:
    container_name: "ms-user"
    build: ./ms-user
    ports:
      - "8081:8081"
    depends_on:
      - banco-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://banco-postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 102030
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_HIBERNATE_SHOW_SQL: true
      JWT_SECRET: e-commerce_secret
      JWT_ISSUER: e-commerce_issuer
    networks:
      - e-commerce

  gestao-itens:
    container_name: "gestao-itens"
    build: ./gestao-itens
    ports:
      - "8082:8082"
    depends_on:
      - banco-mongo
      - ms-user
    environment:
      DB_HOST: banco-mongo
      DB_PORT: 27017
      DB_DATABASE: itens
      MS_USER_URL: http://ms-user:8081
      JWT_SECRET: e-commerce_secret
      JWT_ISSUER: e-commerce_issuer
    networks:
      - e-commerce

  carrinho-compras:
    container_name: "carrinho-compras"
    build:
      context: ./carrinhodecompras
    ports:
      - "8083:8083"
    depends_on:
      - banco-mongo
      - ms-user
      - gestao-itens
    environment:
      DB_HOST: banco-mongo
      DB_PORT: 27017
      DB_DATABASE: db_carrinho
      USUARIO_URL: http://ms-user:8081
      ITENS_URL: http://gestao-itens:8082
      JWT_SECRET: e-commerce_secret
      JWT_ISSUER: e-commerce_issuer
    networks:
      - e-commerce

  pagamento:
    container_name: "pagamento"
    build:
      context: ./ms-pagamento
    ports:
      - "8084:8084"
    depends_on:
      - banco-mongo
      - ms-user
      - carrinho-compras
    environment:
      DB_HOST: banco-mongo
      DB_PORT: 27017
      DB_DATABASE: db_carrinho
      USUARIO_URL: http://ms-user:8081
      ITENS_URL: http://carrinho-compras:8083
      JWT_SECRET: e-commerce_secret
      JWT_ISSUER: e-commerce_issuer
    networks:
      - e-commerce